test_that("run_query returns correct result", {
  temp_db <- fs::file_temp("sqlviewerDB_example", ext = ".db")
  conn <- DBI::dbConnect(RSQLite::SQLite(), dbname = temp_db)
  DBI::dbWriteTable(conn, "iris", iris)
  DBI::dbDisconnect(conn)
  wrong_query_syntax_result <- run_query(parse(text = paste0("connection <- DBI::dbConnect(RSQLite::SQLite(), dbname = ", "'", temp_db, "')")), "SELECTTTT")
  correct_query_syntax_result <- run_query(parse(text = paste0("connection <- DBI::dbConnect(RSQLite::SQLite(), dbname = ", "'", temp_db, "')")), "SELECT * FROM iris")

  expect_s3_class(wrong_query_syntax_result, "data.frame")
  expect_s3_class(correct_query_syntax_result, "data.frame")
  expect_true(nrow(wrong_query_syntax_result) == 1)
  expect_true(nrow(correct_query_syntax_result) == 150)
  expect_length(wrong_query_syntax_result, 1)
  expect_length(correct_query_syntax_result, 5)
})
